<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..'))" />

  <PropertyGroup>
    <NoWarn>$(NoWarn);CA2254;xUnit1051</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>
</Project>
