<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Granit" />
    <PackageReference Include="Granit.Bff" />
    <PackageReference Include="Granit.Bff.Endpoints" />
    <PackageReference Include="Granit.Bff.Yarp" />
    <PackageReference Include="Granit.Caching.StackExchangeRedis" />
    <PackageReference Include="Granit.Http.Cors" />
    <PackageReference Include="Granit.Observability" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GranitMicroservice.ServiceDefaults\GranitMicroservice.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
